// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAdminUser = "admin_user"

// AdminUser mapped from table <admin_user>
type AdminUser struct {
	ID        int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt int64  `gorm:"column:created_at;type:bigint;not null" json:"created_at"`
	UpdatedAt int64  `gorm:"column:updated_at;type:bigint;not null" json:"updated_at"`
	DeletedAt int64  `gorm:"column:deleted_at;type:bigint;not null;uniqueIndex:uniq_username_deleted_at,priority:2" json:"deleted_at"`
	Name      string `gorm:"column:name;type:varchar(64);not null;comment:姓名" json:"name"`                                                         // 姓名
	Username  string `gorm:"column:username;type:varchar(16);not null;uniqueIndex:uniq_username_deleted_at,priority:1;comment:账号" json:"username"` // 账号
	Password  string `gorm:"column:password;type:varchar(255);not null;comment:密码" json:"password"`                                                // 密码
}

// TableName AdminUser's table name
func (*AdminUser) TableName() string {
	return TableNameAdminUser
}
