// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGoodsSku = "goods_sku"

// GoodsSku mapped from table <goods_sku>
type GoodsSku struct {
	ID        int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt int64  `gorm:"column:created_at;type:bigint;not null;index:idx_created_at,priority:1" json:"created_at"`
	UpdatedAt int64  `gorm:"column:updated_at;type:bigint;not null" json:"updated_at"`
	DeletedAt int64  `gorm:"column:deleted_at;type:bigint;not null" json:"deleted_at"`
	GoodsID   int64  `gorm:"column:goods_id;type:bigint;not null;index:idx_goods_id,priority:1;comment:商品id" json:"goods_id"` // 商品id
	SkuTitle  string `gorm:"column:sku_title;type:varchar(255);not null;comment:sku标题" json:"sku_title"`                      // sku标题
	SkuData   string `gorm:"column:sku_data;type:json;not null;comment:sku数据" json:"sku_data"`                                // sku数据
}

// TableName GoodsSku's table name
func (*GoodsSku) TableName() string {
	return TableNameGoodsSku
}
