// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	AdminUser       *adminUser
	Customer        *customer
	CustomerAddress *customerAddress
	Good            *good
	GoodsSku        *goodsSku
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AdminUser = &Q.AdminUser
	Customer = &Q.Customer
	CustomerAddress = &Q.CustomerAddress
	Good = &Q.Good
	GoodsSku = &Q.GoodsSku
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		AdminUser:       newAdminUser(db, opts...),
		Customer:        newCustomer(db, opts...),
		CustomerAddress: newCustomerAddress(db, opts...),
		Good:            newGood(db, opts...),
		GoodsSku:        newGoodsSku(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AdminUser       adminUser
	Customer        customer
	CustomerAddress customerAddress
	Good            good
	GoodsSku        goodsSku
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		AdminUser:       q.AdminUser.clone(db),
		Customer:        q.Customer.clone(db),
		CustomerAddress: q.CustomerAddress.clone(db),
		Good:            q.Good.clone(db),
		GoodsSku:        q.GoodsSku.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		AdminUser:       q.AdminUser.replaceDB(db),
		Customer:        q.Customer.replaceDB(db),
		CustomerAddress: q.CustomerAddress.replaceDB(db),
		Good:            q.Good.replaceDB(db),
		GoodsSku:        q.GoodsSku.replaceDB(db),
	}
}

type queryCtx struct {
	AdminUser       *adminUserDo
	Customer        *customerDo
	CustomerAddress *customerAddressDo
	Good            *goodDo
	GoodsSku        *goodsSkuDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AdminUser:       q.AdminUser.WithContext(ctx),
		Customer:        q.Customer.WithContext(ctx),
		CustomerAddress: q.CustomerAddress.WithContext(ctx),
		Good:            q.Good.WithContext(ctx),
		GoodsSku:        q.GoodsSku.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
